@echo off
setlocal enabledelayedexpansion
title CollaboraNexio - Reset .htaccess
color 0E

echo ==========================================
echo   CollaboraNexio .htaccess Reset Tool
echo   Fix Apache configuration issues
echo ==========================================
echo.

:: Set project path
set PROJECT_PATH=C:\xampp\htdocs\CollaboraNexio
cd /d "%PROJECT_PATH%"

echo [1/5] Backing up current .htaccess...
echo ----------------------------------------
if exist .htaccess (
    set BACKUP_NAME=.htaccess.backup_%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
    set BACKUP_NAME=!BACKUP_NAME: =0!
    copy .htaccess !BACKUP_NAME! >nul 2>&1
    echo Backed up to: !BACKUP_NAME!
) else (
    echo No existing .htaccess found
)
echo.

echo [2/5] Creating minimal .htaccess...
echo ----------------------------------------
(
    echo # CollaboraNexio Minimal .htaccess
    echo # Generated by reset_htaccess.bat
    echo # This is a safe, minimal configuration
    echo.
    echo # Basic Settings
    echo Options -Indexes
    echo Options +FollowSymLinks
    echo.
    echo # Directory Index
    echo DirectoryIndex index.php index.html
    echo.
    echo # Disable directory browsing
    echo ^<IfModule mod_autoindex.c^>
    echo     Options -Indexes
    echo ^</IfModule^>
    echo.
    echo # PHP Settings (if mod_php is used)
    echo ^<IfModule mod_php.c^>
    echo     php_flag display_errors off
    echo     php_flag log_errors on
    echo     php_value error_reporting E_ALL
    echo     php_value max_execution_time 300
    echo     php_value max_input_time 300
    echo     php_value max_input_vars 1000
    echo     php_value memory_limit 256M
    echo     php_value post_max_size 50M
    echo     php_value upload_max_filesize 50M
    echo ^</IfModule^>
    echo.
    echo # Security Headers
    echo ^<IfModule mod_headers.c^>
    echo     Header set X-Content-Type-Options "nosniff"
    echo     Header set X-Frame-Options "SAMEORIGIN"
    echo     Header set X-XSS-Protection "1; mode=block"
    echo ^</IfModule^>
    echo.
    echo # Protect sensitive files
    echo ^<FilesMatch "^\.ht"^>
    echo     Require all denied
    echo ^</FilesMatch^>
    echo.
    echo ^<FilesMatch "\.(ini|log|sh|bak|backup|sql)$"^>
    echo     Require all denied
    echo ^</FilesMatch^>
    echo.
    echo # Protect config files
    echo ^<Files "config.php"^>
    echo     Require all denied
    echo ^</Files^>
    echo.
    echo # Allow access to assets
    echo ^<FilesMatch "\.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$"^>
    echo     Require all granted
    echo ^</FilesMatch^>
) > .htaccess.minimal

echo Created .htaccess.minimal
echo.

echo [3/5] Testing configurations...
echo ----------------------------------------

:: Test 1: No .htaccess
echo Test 1: No .htaccess
if exist .htaccess del .htaccess >nul 2>&1
timeout /t 1 >nul
curl -s -o nul -w "Response: %%{http_code}\n" http://localhost/CollaboraNexio/diagnostic.php
echo.

:: Test 2: Minimal .htaccess
echo Test 2: Minimal .htaccess
copy .htaccess.minimal .htaccess >nul 2>&1
timeout /t 1 >nul
curl -s -o nul -w "Response: %%{http_code}\n" http://localhost/CollaboraNexio/diagnostic.php
echo.

echo [4/5] Creating standard .htaccess...
echo ----------------------------------------
(
    echo # CollaboraNexio Standard .htaccess
    echo # Safe configuration for XAMPP on Windows
    echo.
    echo # Core Settings
    echo Options -Indexes +FollowSymLinks
    echo DirectoryIndex index.php index.html
    echo.
    echo # Enable Rewrite Engine (commented out by default)
    echo # Uncomment these lines if you need URL rewriting
    echo # ^<IfModule mod_rewrite.c^>
    echo #     RewriteEngine On
    echo #     RewriteBase /CollaboraNexio/
    echo #
    echo #     # Redirect to HTTPS (uncomment if using SSL)
    echo #     # RewriteCond %%{HTTPS} off
    echo #     # RewriteRule ^^(.*)$ https://%%{HTTP_HOST}/%%{REQUEST_URI} [L,R=301]
    echo #
    echo #     # Remove trailing slash
    echo #     RewriteCond %%{REQUEST_FILENAME} !-d
    echo #     RewriteRule ^^(.*)/$ /$1 [L,R=301]
    echo #
    echo #     # Handle Front Controller
    echo #     RewriteCond %%{REQUEST_FILENAME} !-f
    echo #     RewriteCond %%{REQUEST_FILENAME} !-d
    echo #     RewriteRule ^^(.*)$ index.php?url=$1 [QSA,L]
    echo # ^</IfModule^>
    echo.
    echo # PHP Configuration
    echo ^<IfModule mod_php.c^>
    echo     php_flag display_errors off
    echo     php_flag log_errors on
    echo     php_value error_reporting E_ALL
    echo     php_value max_execution_time 300
    echo     php_value memory_limit 256M
    echo     php_value post_max_size 50M
    echo     php_value upload_max_filesize 50M
    echo     php_value session.cookie_httponly 1
    echo     php_value session.use_only_cookies 1
    echo ^</IfModule^>
    echo.
    echo # Security
    echo ^<IfModule mod_headers.c^>
    echo     Header set X-Content-Type-Options "nosniff"
    echo     Header set X-Frame-Options "SAMEORIGIN"
    echo     Header set X-XSS-Protection "1; mode=block"
    echo     Header set Referrer-Policy "strict-origin-when-cross-origin"
    echo ^</IfModule^>
    echo.
    echo # Compression
    echo ^<IfModule mod_deflate.c^>
    echo     AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript
    echo     AddOutputFilterByType DEFLATE application/javascript application/x-javascript
    echo     AddOutputFilterByType DEFLATE application/json application/xml application/rss+xml
    echo ^</IfModule^>
    echo.
    echo # Caching
    echo ^<IfModule mod_expires.c^>
    echo     ExpiresActive On
    echo     ExpiresByType image/jpg "access 1 year"
    echo     ExpiresByType image/jpeg "access 1 year"
    echo     ExpiresByType image/gif "access 1 year"
    echo     ExpiresByType image/png "access 1 year"
    echo     ExpiresByType text/css "access 1 month"
    echo     ExpiresByType application/javascript "access 1 month"
    echo ^</IfModule^>
    echo.
    echo # File Protection
    echo ^<FilesMatch "^\.ht"^>
    echo     Require all denied
    echo ^</FilesMatch^>
    echo.
    echo ^<FilesMatch "\.(ini|log|sh|inc|bak|backup|sql|config)$"^>
    echo     Require all denied
    echo ^</FilesMatch^>
    echo.
    echo # Protect sensitive PHP files
    echo ^<FilesMatch "(config|database|credentials)\.php$"^>
    echo     Require all denied
    echo ^</FilesMatch^>
    echo.
    echo # Allow API access
    echo ^<FilesMatch "\.php$"^>
    echo     ^<If "%%{REQUEST_URI} =~ m#^/CollaboraNexio/api/#"^>
    echo         Require all granted
    echo     ^</If^>
    echo ^</FilesMatch^>
) > .htaccess.standard

echo Created .htaccess.standard
copy .htaccess.standard .htaccess >nul 2>&1
echo Applied standard configuration
echo.

echo [5/5] Creating troubleshooting versions...
echo ----------------------------------------

:: Ultra-minimal version
(
    echo # Ultra-minimal .htaccess - For testing only
    echo DirectoryIndex index.php
) > .htaccess.ultra-minimal

:: No-rewrite version
(
    echo # No-rewrite .htaccess - Basic security only
    echo Options -Indexes
    echo DirectoryIndex index.php index.html
    echo.
    echo ^<FilesMatch "^\.ht"^>
    echo     Require all denied
    echo ^</FilesMatch^>
) > .htaccess.no-rewrite

echo Created troubleshooting versions:
echo - .htaccess.ultra-minimal (bare minimum)
echo - .htaccess.no-rewrite (no mod_rewrite)
echo - .htaccess.minimal (basic safe config)
echo - .htaccess.standard (full featured)
echo.

echo ==========================================
echo   Reset Complete!
echo ==========================================
echo.
echo Current .htaccess: Standard configuration
echo.
echo To switch configurations:
echo   copy .htaccess.minimal .htaccess
echo   copy .htaccess.standard .htaccess
echo   copy .htaccess.ultra-minimal .htaccess
echo   copy .htaccess.no-rewrite .htaccess
echo.
echo To restore original:
echo   copy .htaccess.backup_[date] .htaccess
echo.
echo Test your site: http://localhost/CollaboraNexio/
echo.

pause