-- Migration 40: ISO 9001 Requirements Catalog (internal, tenant 28 tooling)
-- - Creates compliance_requirements_catalog
-- - Seeds a minimal but useful ISO 9001:2015+Amd1:2024 operational catalog (NO standard text)
--
-- Safe to re-run:
-- - Table create is IF NOT EXISTS
-- - Seed uses INSERT ... ON DUPLICATE KEY UPDATE

START TRANSACTION;

CREATE TABLE IF NOT EXISTS compliance_requirements_catalog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  standard_code VARCHAR(50) NOT NULL,
  edition VARCHAR(50) NOT NULL,
  clause VARCHAR(20) NOT NULL,
  section VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  intent_summary TEXT NOT NULL,
  evidence_examples_json JSON NULL,
  artifacts_json JSON NULL,
  special_notes_json JSON NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_req (standard_code, edition, clause),
  INDEX idx_std (standard_code, edition, is_active, sort_order),
  INDEX idx_section (standard_code, edition, section, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed (ISO 9001:2015+Amd1:2024) - operational summaries (no standard text)
INSERT INTO compliance_requirements_catalog
  (standard_code, edition, clause, section, title, intent_summary, evidence_examples_json, artifacts_json, special_notes_json, sort_order, is_active)
VALUES
  ('ISO 9001', '2015+Amd1:2024', '4.1', 'Context', 'Contesto e fattori rilevanti',
   'Identificare fattori interni/esterni che influenzano scopo, risultati e direzione del QMS. Riesaminare periodicamente e aggiornare decisioni e rischi collegati.',
   '["analisi contesto (PESTEL/SWOT)","elenco fattori interni/esterni","mappa rischi di contesto","verbali di riesame contesto"]',
   '[{"artifact_type":"analysis","title":"Analisi del contesto","doc_code_hint":"QMS-CTX-01","outline":["perimetro","fattori esterni","fattori interni","impatti su QMS","riesami e aggiornamenti"],"repository_path_hint":"/IMS/02_QMS/01_Context/","mandatory":true}]',
   '["Amd1:2024: includere esplicitamente climate change tra i fattori di contesto rilevanti."]',
   401, 1),
  ('ISO 9001', '2015+Amd1:2024', '4.2', 'Context', 'Parti interessate e bisogni/aspettative',
   'Identificare parti interessate rilevanti e i requisiti/aspettative che impattano il QMS (clienti, autorità, personale, fornitori, comunità). Tenere traccia e aggiornare.',
   '["mappa stakeholder","registro requisiti parti interessate","evidenze contrattuali/regolatorie","riesami periodici"]',
   '[{"artifact_type":"register","title":"Registro parti interessate e requisiti","doc_code_hint":"QMS-CTX-02","outline":["stakeholder","bisogni/aspettative","requisiti applicabili","fonti","riesame","azioni"],"repository_path_hint":"/IMS/02_QMS/01_Context/","mandatory":true}]',
   '["Amd1:2024: considerare climate change anche nelle parti interessate (es. clienti, autorità, comunità)."]',
   402, 1),
  ('ISO 9001', '2015+Amd1:2024', '4.3', 'Context', 'Scopo del QMS',
   'Definire e mantenere lo scopo del QMS (confini, prodotti/servizi, siti, esclusioni motivate). Assicurare coerenza con contesto e requisiti applicabili.',
   '["documento scopo","mappa siti/processi inclusi","motivazioni esclusioni","comunicazione scopo"]',
   '[{"artifact_type":"document","title":"Scopo del QMS","doc_code_hint":"QMS-SCP-01","outline":["azienda","sedi incluse","prodotti/servizi","confini","esclusioni motivate","interfacce esterne"],"repository_path_hint":"/IMS/02_QMS/01_Context/","mandatory":true}]',
   '[]',
   403, 1),
  ('ISO 9001', '2015+Amd1:2024', '4.4', 'Context', 'Processi del QMS (mappa, KPI, interazioni)',
   'Definire i processi del QMS: input/output, sequenze e interazioni, criteri/metodi, risorse, responsabilità, KPI e rischi di processo. Mantenere informazioni documentate adeguate.',
   '["mappa processi","schede processo","KPI e obiettivi","riesami processi","azioni su performance"]',
   '[{"artifact_type":"model","title":"Mappa processi e interazioni","doc_code_hint":"QMS-PROC-01","outline":["processi core/supporto/direzione","interazioni","input/output","owner","KPI"],"repository_path_hint":"/IMS/02_QMS/02_Process_Map/","mandatory":true},{"artifact_type":"template","title":"Scheda processo (template)","doc_code_hint":"QMS-PROC-TPL","outline":["scopo","input/output","indicatori","rischi","controlli","record"],"repository_path_hint":"/IMS/02_QMS/02_Process_Map/","mandatory":false}]',
   '[]',
   404, 1),

  ('ISO 9001', '2015+Amd1:2024', '5.1', 'Leadership', 'Leadership e impegno',
   'Dimostrare leadership sul QMS: integrazione nei processi, risorse, focus cliente, promozione miglioramento e cultura qualità. Assegnare responsabilità e sostenere il sistema.',
   '["evidenze decisioni direzione","allocazione risorse","comunicazioni interne","azioni su rischi/opportunità"]',
   '[{"artifact_type":"evidence_pack","title":"Evidenze leadership (raccolta)","doc_code_hint":"QMS-LDR-01","outline":["decisioni","risorse","priorità qualità","azioni correttive/preventive"],"repository_path_hint":"/IMS/02_QMS/03_Leadership/","mandatory":false}]',
   '[]',
   501, 1),
  ('ISO 9001', '2015+Amd1:2024', '5.2', 'Leadership', 'Politica Qualità',
   'Definire, approvare e comunicare la politica qualità. Assicurare che sia appropriata allo scopo e che includa impegni a soddisfare requisiti e migliorare continuamente.',
   '["politica pubblicata","comunicazione a personale","riesami periodici","coerenza con obiettivi"]',
   '[{"artifact_type":"policy","title":"Politica Qualità","doc_code_hint":"QMS-POL-01","outline":["scopo e principi","impegni","applicazione","riesame"],"repository_path_hint":"/IMS/02_QMS/03_Leadership/","mandatory":true}]',
   '[]',
   502, 1),
  ('ISO 9001', '2015+Amd1:2024', '5.3', 'Leadership', 'Ruoli, responsabilità e autorità',
   'Chiarire ruoli e responsabilità del QMS: chi fa cosa, chi approva, chi monitora performance e conformità, chi gestisce cambiamenti e non conformità.',
   '["organigramma/ruoli","job description","matrice responsabilità (RACI)","nomine/lettere incarico"]',
   '[{"artifact_type":"matrix","title":"Matrice responsabilità (RACI) QMS","doc_code_hint":"QMS-RACI-01","outline":["processi","ruoli","responsabile/approvatore/consultato/informato"],"repository_path_hint":"/IMS/02_QMS/03_Leadership/","mandatory":true}]',
   '[]',
   503, 1),

  ('ISO 9001', '2015+Amd1:2024', '6.1', 'Planning', 'Rischi e opportunità (registro e azioni)',
   'Determinare rischi/opportunità del QMS e pianificare azioni proporzionate. Integrare nel QMS e valutare efficacia delle azioni.',
   '["registro rischi/opportunità","piani di trattamento","riesami efficacia","collegamenti a KPI e audit"]',
   '[{"artifact_type":"register","title":"Registro rischi e opportunità","doc_code_hint":"QMS-RISK-01","outline":["contesto","rischi","opportunità","azioni","owner","scadenze","stato","verifica efficacia"],"repository_path_hint":"/IMS/02_QMS/04_Planning/","mandatory":true}]',
   '[]',
   601, 1),
  ('ISO 9001', '2015+Amd1:2024', '6.2', 'Planning', 'Obiettivi Qualità e piano',
   'Definire obiettivi misurabili, coerenti con la politica, monitorati e aggiornati. Pianificare come raggiungerli (azioni, risorse, responsabili, tempi, misure).',
   '["obiettivi e KPI","piani azione","riesami periodici","evidenze avanzamento"]',
   '[{"artifact_type":"plan","title":"Obiettivi Qualità e piano di azione","doc_code_hint":"QMS-OBJ-01","outline":["obiettivi","metriche","baseline/target","azioni","owner","scadenze","risorse","stato"],"repository_path_hint":"/IMS/02_QMS/04_Planning/","mandatory":true}]',
   '[]',
   602, 1),
  ('ISO 9001', '2015+Amd1:2024', '6.3', 'Planning', 'Pianificazione delle modifiche',
   'Gestire i cambiamenti al QMS in modo pianificato: valutare impatti, risorse, responsabilità, rischi e mantenere integrità del sistema.',
   '["change log","valutazioni impatto","approvazioni","comunicazioni"]',
   '[{"artifact_type":"register","title":"Registro cambiamenti QMS","doc_code_hint":"QMS-CHG-01","outline":["descrizione cambio","motivo","impatti","rischi","approvazioni","esecuzione","verifica"],"repository_path_hint":"/IMS/02_QMS/04_Planning/","mandatory":false}]',
   '[]',
   603, 1),

  ('ISO 9001', '2015+Amd1:2024', '7.1', 'Support', 'Risorse (persone, infrastrutture, ambiente, monitoraggi)',
   'Determinare e fornire risorse necessarie per processi e conformità: persone, infrastrutture, ambiente di lavoro, strumenti di monitoraggio/misura e conoscenza organizzativa.',
   '["piani risorse","manutenzioni","tarature/verifiche","inventari","knowledge base"]',
   '[{"artifact_type":"register","title":"Registro risorse e strumenti di misura","doc_code_hint":"QMS-RES-01","outline":["asset","uso","responsabile","taratura/verifica","scadenze","evidenze"],"repository_path_hint":"/IMS/02_QMS/05_Support/","mandatory":false}]',
   '[]',
   701, 1),
  ('ISO 9001', '2015+Amd1:2024', '7.2', 'Support', 'Competenza (matrice + formazione)',
   'Assicurare competenza per ruoli che impattano qualità: definire requisiti, valutare competenze, formare dove necessario e mantenere evidenze.',
   '["matrice competenze","piani formazione","valutazioni efficacia","attestati"]',
   '[{"artifact_type":"matrix","title":"Matrice competenze","doc_code_hint":"QMS-HR-01","outline":["ruolo","competenze richieste","livello","gap","azioni formazione","evidenze"],"repository_path_hint":"/IMS/02_QMS/05_Support/02_People/","mandatory":true},{"artifact_type":"plan","title":"Piano formazione","doc_code_hint":"QMS-HR-02","outline":["fabbisogni","calendario","partecipanti","valutazione efficacia"],"repository_path_hint":"/IMS/02_QMS/05_Support/02_People/","mandatory":false}]',
   '[]',
   702, 1),
  ('ISO 9001', '2015+Amd1:2024', '7.3', 'Support', 'Consapevolezza',
   'Rendere il personale consapevole di politica/obiettivi, contributo al QMS, implicazioni di non conformità e miglioramento. Usare comunicazioni e briefing.',
   '["briefing","materiale comunicazione","quiz/valutazioni","campagne interne"]',
   '[{"artifact_type":"plan","title":"Piano comunicazione/consapevolezza qualità","doc_code_hint":"QMS-AWR-01","outline":["messaggi chiave","target","canali","frequenza","evidenze"],"repository_path_hint":"/IMS/02_QMS/05_Support/02_People/","mandatory":false}]',
   '[]',
   703, 1),
  ('ISO 9001', '2015+Amd1:2024', '7.4', 'Support', 'Comunicazione (interna/esterna)',
   'Determinare cosa comunicare, a chi, quando e come (interno/esterno), inclusi temi qualità, clienti, autorità e fornitori. Tenere evidenze dove opportuno.',
   '["piani comunicazione","template email/avvisi","log comunicazioni critiche","comunicazioni cliente"]',
   '[{"artifact_type":"procedure","title":"Procedura comunicazioni QMS","doc_code_hint":"QMS-COM-01","outline":["canali","ruoli","escalation","registrazioni"],"repository_path_hint":"/IMS/02_QMS/05_Support/03_Communication/","mandatory":false}]',
   '[]',
   704, 1),
  ('ISO 9001', '2015+Amd1:2024', '7.5', 'Support', 'Informazioni documentate (controllo documenti/registrazioni)',
   'Creare e controllare informazioni documentate: approvazione, distribuzione, accesso, versioni, conservazione e protezione. Assicurare tracciabilità delle modifiche.',
   '["procedura gestione documenti","registro revisioni","controllo accessi","evidenze conservazione"]',
   '[{"artifact_type":"procedure","title":"Procedura gestione documenti e registrazioni","doc_code_hint":"QMS-DOC-01","outline":["creazione","approvazione","versioning","distribuzione","archiviazione","backup","retention"],"repository_path_hint":"/IMS/02_QMS/05_Support/01_Documented_Information/","mandatory":true},{"artifact_type":"register","title":"Registro revisioni documenti","doc_code_hint":"QMS-DOC-REG","outline":["doc_code","titolo","versione","data","approvatore","note"],"repository_path_hint":"/IMS/02_QMS/05_Support/01_Documented_Information/","mandatory":true}]',
   '[]',
   705, 1),

  ('ISO 9001', '2015+Amd1:2024', '8.1', 'Operation', 'Pianificazione e controllo operativi',
   'Pianificare, implementare e controllare processi operativi per garantire requisiti su prodotti/servizi. Definire criteri, controlli, risorse e gestire output non conformi.',
   '["piani operativi","work instructions","checklist","monitoraggi"]',
   '[{"artifact_type":"procedure","title":"Procedura controllo operativo","doc_code_hint":"QMS-OPS-01","outline":["pianificazione","controlli","criteri accettazione","gestione output","registrazioni"],"repository_path_hint":"/IMS/02_QMS/06_Operation/","mandatory":false}]',
   '[]',
   801, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.2', 'Operation', 'Requisiti per prodotti/servizi (cliente)',
   'Determinare, riesaminare e comunicare requisiti cliente (contrattuali, legali, impliciti). Gestire cambiamenti e assicurare capacità di soddisfarli.',
   '["riesame ordine/contratto","offerte","conferme","tracciamento requisiti"]',
   '[{"artifact_type":"template","title":"Checklist riesame requisiti cliente","doc_code_hint":"QMS-CUS-CHK","outline":["requisiti dichiarati","requisiti impliciti","requisiti legali","fattibilità","cambiamenti"],"repository_path_hint":"/IMS/02_QMS/06_Operation/01_Customer/","mandatory":false}]',
   '[]',
   802, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.3', 'Operation', 'Progettazione e sviluppo (se applicabile)',
   'Gestire progettazione/sviluppo: pianificazione, input/output, riesami, verifiche/validazioni e controllo modifiche. Applicabile solo se l’organizzazione progetta/sviluppa.',
   '["piani progetto","riesami design","verifiche/validazioni","gestione modifiche"]',
   '[{"artifact_type":"procedure","title":"Procedura progettazione e sviluppo (se applicabile)","doc_code_hint":"QMS-DES-01","outline":["fasi","input","output","riesami","verifica/validazione","cambiamenti"],"repository_path_hint":"/IMS/02_QMS/06_Operation/02_Design/","mandatory":false}]',
   '["Se non applicabile, documentare la motivazione nello scopo e nei processi."]',
   803, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.4', 'Operation', 'Controllo processi/forniture esterne',
   'Assicurare che prodotti/servizi esterni soddisfino requisiti: criteri selezione e valutazione fornitori, controlli in ingresso, monitoraggio performance e azioni su fornitori non conformi.',
   '["albo fornitori","valutazioni periodiche","criteri qualifica","audit fornitori","NC fornitori"]',
   '[{"artifact_type":"register","title":"Albo fornitori qualificati + valutazione","doc_code_hint":"QMS-SUP-01","outline":["fornitore","ambito","criteri","valutazioni","riesami","azioni"],"repository_path_hint":"/IMS/02_QMS/06_Operation/03_Suppliers/","mandatory":true}]',
   '[]',
   804, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.5.1', 'Operation', 'Erogazione (controllo produzione/servizio)',
   'Erogare prodotti/servizi in condizioni controllate: istruzioni, criteri, risorse, competenze e tracciabilità dove necessario.',
   '["istruzioni operative","checklist erogazione","registrazioni controlli","tracciabilità"]',
   '[{"artifact_type":"template","title":"Checklist controllo erogazione","doc_code_hint":"QMS-SVC-CHK","outline":["fasi","controlli","criteri","esiti","firma"],"repository_path_hint":"/IMS/02_QMS/06_Operation/04_Delivery/","mandatory":false}]',
   '[]',
   851, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.5.2', 'Operation', 'Identificazione e tracciabilità (se richiesta)',
   'Assicurare identificazione e tracciabilità quando richiesto da requisiti/leggi/contratti. Definire regole e registrazioni.',
   '["codifiche lotto/commessa","etichette","registri tracciabilità","log sistemi"]',
   '[{"artifact_type":"procedure","title":"Procedura identificazione e tracciabilità (se applicabile)","doc_code_hint":"QMS-TRC-01","outline":["quando applica","regole codifica","registrazioni","responsabilità"],"repository_path_hint":"/IMS/02_QMS/06_Operation/04_Delivery/","mandatory":false}]',
   '["Applicabilità dipende da settore/prodotto/servizio."]',
   852, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.5.3', 'Operation', 'Proprietà del cliente/fornitori esterni',
   'Gestire e proteggere proprietà del cliente o di terzi (materiale, dati, IP). Segnalare danni/perdite e mantenere evidenze.',
   '["registro beni/dati cliente","policy accesso","incident log","comunicazioni al cliente"]',
   '[{"artifact_type":"procedure","title":"Procedura gestione proprietà del cliente","doc_code_hint":"QMS-CUST-PROP","outline":["ricezione","uso","protezione","restituzione","incidenti"],"repository_path_hint":"/IMS/02_QMS/06_Operation/01_Customer/","mandatory":false}]',
   '[]',
   853, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.5.5', 'Operation', 'Attività post-consegna (se applicabile)',
   'Definire e controllare attività post-consegna quando applicabili (assistenza, garanzia, manutenzione, richiami).',
   '["SLA/assistenza","registri interventi","ticket","report manutenzione"]',
   '[{"artifact_type":"process","title":"Processo post-consegna (assistenza/garanzia)","doc_code_hint":"QMS-AFTER-01","outline":["canali","tempi","responsabilità","registrazioni","analisi reclami"],"repository_path_hint":"/IMS/02_QMS/06_Operation/05_After_Delivery/","mandatory":false}]',
   '["Applicabilità dipende da contratto e settore."]',
   855, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.6', 'Operation', 'Rilascio di prodotti/servizi',
   'Definire criteri di accettazione e assicurare che verifiche siano completate prima del rilascio. Mantenere evidenze di conformità e autorizzazioni.',
   '["checklist accettazione","record collaudo/verifica","approvazioni rilascio","tracciamento non conformità"]',
   '[{"artifact_type":"template","title":"Registro/Checklist rilascio","doc_code_hint":"QMS-REL-01","outline":["criteri","verifiche","esito","approvatore","data"],"repository_path_hint":"/IMS/02_QMS/06_Operation/04_Delivery/","mandatory":false}]',
   '[]',
   806, 1),
  ('ISO 9001', '2015+Amd1:2024', '8.7', 'Operation', 'Gestione output non conforme',
   'Identificare e controllare output non conformi per prevenire uso/erogazione non intenzionale. Definire azioni (correzione, segregazione, concessione) e registrare decisioni.',
   '["registro NC prodotto/servizio","azioni correttive immediate","concessioni approvate","evidenze segregazione"]',
   '[{"artifact_type":"register","title":"Registro non conformità operative","doc_code_hint":"QMS-NC-OPS","outline":["descrizione","causa","azione immediata","decisione","owner","evidenze","stato"],"repository_path_hint":"/IMS/02_QMS/07_Performance/03_Nonconformities/","mandatory":true}]',
   '[]',
   807, 1),

  ('ISO 9001', '2015+Amd1:2024', '9.1', 'Performance', 'Monitoraggio, misurazione, analisi e valutazione',
   'Definire cosa misurare, come, quando e come analizzare risultati. Usare dati per valutare performance processi, soddisfazione cliente e miglioramento.',
   '["cruscotto KPI","report periodici","analisi trend","azioni su scostamenti"]',
   '[{"artifact_type":"dashboard","title":"Cruscotto KPI QMS","doc_code_hint":"QMS-KPI-01","outline":["KPI per processo","trend","target","azioni"],"repository_path_hint":"/IMS/02_QMS/07_Performance/01_KPI/","mandatory":true}]',
   '[]',
   901, 1),
  ('ISO 9001', '2015+Amd1:2024', '9.2', 'Performance', 'Audit interno (piano + report)',
   'Pianificare ed eseguire audit interni per verificare conformità e efficacia del QMS. Definire programma, criteri, competenze auditor, report e follow-up.',
   '["piano audit","checklist audit","rapporti audit","azioni su rilievi","verifica efficacia"]',
   '[{"artifact_type":"plan","title":"Programma audit interno","doc_code_hint":"QMS-AUD-PLAN","outline":["ambito","frequenza","criteri","auditor","calendario","reporting"],"repository_path_hint":"/IMS/02_QMS/07_Performance/02_Internal_Audit/","mandatory":true},{"artifact_type":"template","title":"Rapporto audit interno (template)","doc_code_hint":"QMS-AUD-REP","outline":["scopo","criteri","evidenze","rilievi","azioni"],"repository_path_hint":"/IMS/02_QMS/07_Performance/02_Internal_Audit/","mandatory":true}]',
   '[]',
   902, 1),
  ('ISO 9001', '2015+Amd1:2024', '9.3', 'Performance', 'Riesame della direzione (input/output)',
   'Eseguire riesami periodici della direzione: valutare performance, rischi, risorse, cambiamenti e opportunità di miglioramento. Documentare input/output e decisioni.',
   '["verbali riesame","azioni e decisioni","riesame KPI","riesame rischi","riesame audit/NC"]',
   '[{"artifact_type":"minutes","title":"Verbale riesame di direzione","doc_code_hint":"QMS-MR-01","outline":["input richiesti","decisioni","azioni","risorse","cambiamenti","follow-up"],"repository_path_hint":"/IMS/02_QMS/07_Performance/04_Management_Review/","mandatory":true}]',
   '[]',
   903, 1),

  ('ISO 9001', '2015+Amd1:2024', '10.1', 'Improvement', 'Miglioramento (opportunità e azioni)',
   'Identificare opportunità di miglioramento e implementare azioni per aumentare soddisfazione cliente e performance del QMS.',
   '["backlog miglioramenti","Kaizen/azioni","benefici misurati","riesami"]',
   '[{"artifact_type":"register","title":"Registro opportunità di miglioramento","doc_code_hint":"QMS-IMP-01","outline":["idea","fonte","priorità","azione","owner","beneficio","stato"],"repository_path_hint":"/IMS/02_QMS/08_Improvement/","mandatory":false}]',
   '[]',
   1001, 1),
  ('ISO 9001', '2015+Amd1:2024', '10.2', 'Improvement', 'Non conformità e azioni correttive (con efficacia)',
   'Gestire non conformità: contenimento, analisi causa, azioni correttive, aggiornamenti rischi/processi e verifica efficacia. Mantenere tracciabilità completa.',
   '["registro NC","analisi causa (5Why/Ishikawa)","piano azioni","verifica efficacia","chiusura"]',
   '[{"artifact_type":"register","title":"Registro NC e azioni correttive","doc_code_hint":"QMS-CAPA-01","outline":["NC","causa","azioni","responsabile","scadenze","evidenze","verifica efficacia","chiusura"],"repository_path_hint":"/IMS/02_QMS/08_Improvement/02_NC_CAPA/","mandatory":true}]',
   '[]',
   1002, 1),
  ('ISO 9001', '2015+Amd1:2024', '10.3', 'Improvement', 'Miglioramento continuo',
   'Mantenere un meccanismo continuo per migliorare adeguatezza, efficacia e idoneità del QMS (trend, feedback, audit, NC, obiettivi).',
   '["trend KPI","riesami periodici","lezioni apprese","azioni preventive/priorità"]',
   '[{"artifact_type":"process","title":"Processo miglioramento continuo","doc_code_hint":"QMS-CI-01","outline":["input","valutazione","prioritizzazione","azioni","verifica"],"repository_path_hint":"/IMS/02_QMS/08_Improvement/","mandatory":false}]',
   '[]',
   1003, 1)
ON DUPLICATE KEY UPDATE
  section = VALUES(section),
  title = VALUES(title),
  intent_summary = VALUES(intent_summary),
  evidence_examples_json = VALUES(evidence_examples_json),
  artifacts_json = VALUES(artifacts_json),
  special_notes_json = VALUES(special_notes_json),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

COMMIT;

